services:
  postgres:
    image: postgres:14
    container_name: postgres-setis
    restart: always
    environment:
      POSTGRES_USER: setis
      POSTGRES_PASSWORD: setis123
      POSTGRES_DB: usuarios
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: setis-api
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/usuarios
      SPRING_DATASOURCE_USERNAME: setis
      SPRING_DATASOURCE_PASSWORD: setis123
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    ports:
      - "8080:8080"

volumes:
  postgres_data:
